use_default_settings: true

server:
  secret_key: "change-me-please"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  autocomplete: "google"
  formats:
    - html
    - json

ui:
  static_use_hash: true
  default_theme: simple
