"""Formatting utilities for MindFlow backend.

Functions for formatting, parsing, and converting data.
"""

from .formatters import (
    format_sse,
    format_bytes,
    format_duration,
    format_currency,
    format_percentage,
    format_number,
    format_datetime_iso,
    format_datetime_human,
    format_list,
    format_key_value,
    format_code_block,
    format_error_message,
    format_phone_number,
    format_url_safe,
    format_file_size,
    format_memory_usage,
)

from .parsers import (
    extract_json_from_response,
    parse_csv,
    parse_json_safe,
    parse_datetime_iso,
    parse_date_string,
    parse_url,
    parse_query_string,
    parse_phone_number,
    parse_markdown_links,
    parse_hashtags,
    parse_mentions,
    parse_file_size,
    parse_duration,
    parse_version,
    parse_ip_address,
    parse_user_agent,
    parse_boolean,
)

from .converters import (
    to_json,
    from_json,
    to_bool,
    to_int,
    to_float,
    to_str,
    to_list,
    to_dict,
    to_uuid,
    to_datetime,
    to_base64,
    from_base64,
    to_hash,
    to_snake_case,
    to_camel_case,
    to_pascal_case,
    to_kebab_case,
    to_slug,
    bytes_to_human,
    human_to_bytes,
)

__all__ = [
    # Formatters
    "format_sse",
    "format_bytes",
    "format_duration",
    "format_currency",
    "format_percentage",
    "format_number",
    "format_datetime_iso",
    "format_datetime_human",
    "format_list",
    "format_key_value",
    "format_code_block",
    "format_error_message",
    "format_phone_number",
    "format_url_safe",
    "format_file_size",
    "format_memory_usage",
    
    # Parsers
    "extract_json_from_response",
    "parse_csv",
    "parse_json_safe",
    "parse_datetime_iso",
    "parse_date_string",
    "parse_url",
    "parse_query_string",
    "parse_phone_number",
    "parse_markdown_links",
    "parse_hashtags",
    "parse_mentions",
    "parse_file_size",
    "parse_duration",
    "parse_version",
    "parse_ip_address",
    "parse_user_agent",
    "parse_boolean",
    
    # Converters
    "to_json",
    "from_json",
    "to_bool",
    "to_int",
    "to_float",
    "to_str",
    "to_list",
    "to_dict",
    "to_uuid",
    "to_datetime",
    "to_base64",
    "from_base64",
    "to_hash",
    "to_snake_case",
    "to_camel_case",
    "to_pascal_case",
    "to_kebab_case",
    "to_slug",
    "bytes_to_human",
    "human_to_bytes",
]
