"""Task Management Service - Core business logic for task CRUD and dependency management."""

from __future__ import annotations

import asyncio
from datetime import UTC, datetime
from typing import Any

from sqlalchemy import and_, delete, func, or_, select, update
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import selectinload

from mindflow_backend.api.websocket.task_updates import (
    TaskUpdateMessage,
    TaskUpdateWebSocketManager,
)
from mindflow_backend.exceptions.tasks import (
    CircularDependencyError,
    InvalidStatusTransitionError,
    TaskDependencyError,
    TaskNotFoundError,
    TaskVersionConflictError,
)
from mindflow_backend.hooks.handlers.task_lifecycle import TaskCompletedHandler, TaskCreatedHandler
from mindflow_backend.infra.database.connection import get_db_session
from mindflow_backend.infra.logging import get_logger
from mindflow_backend.schemas.tasks import TaskCreate, TaskListResponse, TaskResponse, TaskUpdate
from mindflow_backend.services.interfaces.base_interfaces import BaseAbstractService
from mindflow_backend.storage.postgresql.models import Task, TaskDependency

_logger = get_logger(__name__)


class TaskManagementService(BaseAbstractService):
    """Service for managing tasks with persistent storage and dependency graph."""

    def __init__(self) -> None:
        super().__init__()
        self._lock = asyncio.Lock()

    def _get_logger(self) -> Any:
        """Get logger instance for this service."""
        return _logger

    async def create_task(
        self,
        task_data: TaskCreate,
        session_id: str | None = None,
    ) -> TaskResponse:
        """Create a new task with auto-generated ID.

        Args:
            task_data: Task creation data
            session_id: Optional session ID for context

        Returns:
            Created task response

        Raises:
            CircularDependencyError: If dependencies create a cycle
            TaskDependencyError: If dependency tasks don't exist
        """
        self.log_operation("create_task", task_list_id=task_data.task_list_id)

        async with get_db_session() as db:
            # Create task (ID auto-generated by SERIAL)
            task = Task(
                task_list_id=task_data.task_list_id,
                subject=task_data.subject,
                description=task_data.description,
                active_form=task_data.active_form,
                owner=task_data.owner,
                status=task_data.status,
                task_metadata=task_data.task_metadata,
                created_at=datetime.now(UTC),
                updated_at=datetime.now(UTC),
                version=1,
            )

            db.add(task)
            await db.flush()  # Get the auto-generated task ID

            # Create dependency relationships
            if task_data.blocks:
                await self._add_dependencies(db, task.id, task_data.blocks, is_blocks=True)

            if task_data.blocked_by:
                await self._add_dependencies(db, task.id, task_data.blocked_by, is_blocks=False)

            await db.commit()
            await db.refresh(task)

            # Load dependencies
            blocks_ids = await self._get_blocks_ids(db, task.id)
            blocked_by_ids = await self._get_blocked_by_ids(db, task.id)

            _logger.info(
                "task_created",
                task_id=task.id,
                task_list_id=task.task_list_id,
                subject=task.subject,
            )

            # Trigger TaskCreated hook
            if session_id:
                try:
                    async for hook_result in TaskCreatedHandler.execute(
                        session_id=session_id,
                        task_id=str(task.id),
                        task_name=task.subject,
                    ):
                        _logger.debug(
                            "task_created_hook_executed",
                            task_id=task.id,
                            hook_status=hook_result.status,
                        )
                except Exception as exc:
                    _logger.warning(
                        "task_created_hook_failed",
                        task_id=task.id,
                        error=str(exc),
                    )

                # Broadcast WebSocket update
                await self._broadcast_task_update("task_created", task, session_id)

            return self._task_to_response(task, blocks_ids, blocked_by_ids)

    async def get_task(
        self,
        task_id: int,
        include_dependencies: bool = True,
    ) -> TaskResponse:
        """Get a task by ID.

        Args:
            task_id: Task ID
            include_dependencies: Whether to include dependency lists

        Returns:
            Task response

        Raises:
            TaskNotFoundError: If task doesn't exist
        """
        self.log_operation("get_task", task_id=task_id)

        async with get_db_session() as db:
            result = await db.execute(select(Task).where(Task.id == task_id))
            task = result.scalar_one_or_none()

            if not task:
                raise TaskNotFoundError(task_id)

            if include_dependencies:
                blocks_ids = await self._get_blocks_ids(db, task.id)
                blocked_by_ids = await self._get_blocked_by_ids(db, task.id)
            else:
                blocks_ids = []
                blocked_by_ids = []

            return self._task_to_response(task, blocks_ids, blocked_by_ids)

    async def update_task(
        self,
        task_id: int,
        task_data: TaskUpdate,
        session_id: str | None = None,
    ) -> TaskResponse:
        """Update a task with optimistic locking.

        Args:
            task_id: Task ID
            task_data: Task update data
            session_id: Optional session ID for context

        Returns:
            Updated task response

        Raises:
            TaskNotFoundError: If task doesn't exist
            TaskVersionConflictError: If version mismatch (optimistic lock)
            InvalidStatusTransitionError: If status transition is invalid
            CircularDependencyError: If dependencies create a cycle
        """
        self.log_operation("update_task", task_id=task_id)

        async with get_db_session() as db:
            # Lock row for update
            result = await db.execute(
                select(Task).where(Task.id == task_id).with_for_update()
            )
            task = result.scalar_one_or_none()

            if not task:
                raise TaskNotFoundError(task_id)

            # Optimistic locking check
            if task_data.version is not None and task.version != task_data.version:
                raise TaskVersionConflictError(task_id, task_data.version, task.version)

            # Update fields
            updates = {}
            if task_data.subject is not None:
                updates["subject"] = task_data.subject
            if task_data.description is not None:
                updates["description"] = task_data.description
            if task_data.active_form is not None:
                updates["active_form"] = task_data.active_form
            if task_data.owner is not None:
                updates["owner"] = task_data.owner
            if task_data.status is not None:
                # Validate status transition
                self._validate_status_transition(task.status, task_data.status)
                updates["status"] = task_data.status
            if task_data.task_metadata is not None:
                # Merge metadata
                merged_metadata = {**task.task_metadata, **task_data.task_metadata}
                updates["task_metadata"] = merged_metadata

            if updates:
                updates["updated_at"] = datetime.now(UTC)
                updates["version"] = task.version + 1

                await db.execute(
                    update(Task).where(Task.id == task_id).values(**updates)
                )

            # Update dependencies
            if task_data.add_blocks:
                await self._add_dependencies(db, task_id, task_data.add_blocks, is_blocks=True)

            if task_data.remove_blocks:
                await self._remove_dependencies(db, task_id, task_data.remove_blocks, is_blocks=True)

            if task_data.add_blocked_by:
                await self._add_dependencies(db, task_id, task_data.add_blocked_by, is_blocks=False)

            if task_data.remove_blocked_by:
                await self._remove_dependencies(db, task_id, task_data.remove_blocked_by, is_blocks=False)

            await db.commit()

            # Refresh task
            await db.refresh(task)

            blocks_ids = await self._get_blocks_ids(db, task.id)
            blocked_by_ids = await self._get_blocked_by_ids(db, task.id)

            _logger.info(
                "task_updated",
                task_id=task.id,
                updates=list(updates.keys()),
            )

            # Trigger TaskCompleted hook if status changed to completed
            if session_id and "status" in updates and updates["status"] == "completed":
                try:
                    async for hook_result in TaskCompletedHandler.execute(
                        session_id=session_id,
                        task_id=str(task.id),
                        task_name=task.subject,
                    ):
                        _logger.debug(
                            "task_completed_hook_executed",
                            task_id=task.id,
                            hook_status=hook_result.status,
                        )
                except Exception as exc:
                    _logger.warning(
                        "task_completed_hook_failed",
                        task_id=task.id,
                        error=str(exc),
                    )

                # Broadcast WebSocket update for completed task
                await self._broadcast_task_update("task_completed", task, session_id)

            # Broadcast WebSocket update for any task update (if session_id provided)
            elif session_id and updates:
                await self._broadcast_task_update("task_updated", task, session_id)

            return self._task_to_response(task, blocks_ids, blocked_by_ids)

    async def delete_task(self, task_id: int) -> bool:
        """Delete a task (hard delete with cascade).

        Args:
            task_id: Task ID

        Returns:
            True if deleted successfully

        Raises:
            TaskNotFoundError: If task doesn't exist
        """
        self.log_operation("delete_task", task_id=task_id)

        async with get_db_session() as db:
            result = await db.execute(delete(Task).where(Task.id == task_id))
            await db.commit()

            if result.rowcount == 0:
                raise TaskNotFoundError(task_id)

            _logger.info("task_deleted", task_id=task_id)
            return True

    async def list_tasks(
        self,
        task_list_id: str | None = None,
        owner: str | None = None,
        status: str | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> TaskListResponse:
        """List tasks with filtering and pagination.

        Args:
            task_list_id: Filter by task list ID
            owner: Filter by owner
            status: Filter by status
            limit: Maximum number of tasks to return
            offset: Number of tasks to skip

        Returns:
            TaskListResponse with tasks and pagination info
        """
        self.log_operation("list_tasks", task_list_id=task_list_id, owner=owner, status=status)

        async with get_db_session() as db:
            # Build query
            query = select(Task)
            count_query = select(func.count()).select_from(Task)

            filters = []
            if task_list_id:
                filters.append(Task.task_list_id == task_list_id)
            if owner:
                filters.append(Task.owner == owner)
            if status:
                filters.append(Task.status == status)

            if filters:
                query = query.where(and_(*filters))
                count_query = count_query.where(and_(*filters))

            # Get total count
            total_result = await db.execute(count_query)
            total = total_result.scalar() or 0

            # Get tasks with pagination
            query = query.order_by(Task.created_at.desc()).limit(limit).offset(offset)
            result = await db.execute(query)
            tasks = result.scalars().all()

            # Load dependencies for all tasks
            task_responses = []
            for task in tasks:
                blocks_ids = await self._get_blocks_ids(db, task.id)
                blocked_by_ids = await self._get_blocked_by_ids(db, task.id)
                task_responses.append(self._task_to_response(task, blocks_ids, blocked_by_ids))

            return TaskListResponse(
                tasks=task_responses,
                total=total,
                limit=limit,
                offset=offset,
            )

    # Helper methods

    async def _add_dependencies(
        self,
        db: Any,
        task_id: int,
        dependency_ids: list[int],
        is_blocks: bool,
    ) -> None:
        """Add task dependencies.

        Args:
            db: Database session
            task_id: Source task ID
            dependency_ids: List of dependency task IDs
            is_blocks: True if task_id blocks dependency_ids, False if blocked by

        Raises:
            TaskDependencyError: If dependency tasks don't exist
            CircularDependencyError: If dependencies create a cycle
        """
        for dep_id in dependency_ids:
            # Verify dependency task exists
            result = await db.execute(select(Task.id).where(Task.id == dep_id))
            if not result.scalar_one_or_none():
                raise TaskDependencyError(f"Dependency task {dep_id} does not exist")

            # Create dependency relationship
            if is_blocks:
                # task_id blocks dep_id
                dep = TaskDependency(task_id=task_id, blocks_task_id=dep_id)
            else:
                # task_id is blocked by dep_id
                dep = TaskDependency(task_id=dep_id, blocks_task_id=task_id)

            try:
                db.add(dep)
                await db.flush()
            except IntegrityError as e:
                if "task_deps_unique" in str(e):
                    # Dependency already exists, skip
                    await db.rollback()
                    continue
                raise

            # Check for circular dependencies
            if is_blocks:
                await self._detect_circular_dependency(db, task_id, dep_id)
            else:
                await self._detect_circular_dependency(db, dep_id, task_id)

    async def _remove_dependencies(
        self,
        db: Any,
        task_id: int,
        dependency_ids: list[int],
        is_blocks: bool,
    ) -> None:
        """Remove task dependencies.

        Args:
            db: Database session
            task_id: Source task ID
            dependency_ids: List of dependency task IDs to remove
            is_blocks: True if task_id blocks dependency_ids, False if blocked by
        """
        for dep_id in dependency_ids:
            if is_blocks:
                await db.execute(
                    delete(TaskDependency).where(
                        and_(
                            TaskDependency.task_id == task_id,
                            TaskDependency.blocks_task_id == dep_id,
                        )
                    )
                )
            else:
                await db.execute(
                    delete(TaskDependency).where(
                        and_(
                            TaskDependency.task_id == dep_id,
                            TaskDependency.blocks_task_id == task_id,
                        )
                    )
                )

    async def _detect_circular_dependency(
        self,
        db: Any,
        start_task_id: int,
        end_task_id: int,
    ) -> None:
        """Detect circular dependencies using DFS.

        Args:
            db: Database session
            start_task_id: Starting task ID
            end_task_id: Ending task ID

        Raises:
            CircularDependencyError: If a cycle is detected
        """
        visited = set()
        path = []

        async def dfs(task_id: int) -> bool:
            if task_id in path:
                # Cycle detected
                cycle_start = path.index(task_id)
                cycle = path[cycle_start:] + [task_id]
                raise CircularDependencyError(cycle)

            if task_id in visited:
                return False

            visited.add(task_id)
            path.append(task_id)

            # Get all tasks that this task blocks
            result = await db.execute(
                select(TaskDependency.blocks_task_id).where(TaskDependency.task_id == task_id)
            )
            blocked_tasks = result.scalars().all()

            for blocked_id in blocked_tasks:
                await dfs(blocked_id)

            path.pop()
            return False

        await dfs(start_task_id)

    async def _get_blocks_ids(self, db: Any, task_id: int) -> list[int]:
        """Get list of task IDs that this task blocks.

        Args:
            db: Database session
            task_id: Task ID

        Returns:
            List of blocked task IDs
        """
        result = await db.execute(
            select(TaskDependency.blocks_task_id).where(TaskDependency.task_id == task_id)
        )
        return list(result.scalars().all())

    async def _get_blocked_by_ids(self, db: Any, task_id: int) -> list[int]:
        """Get list of task IDs that block this task.

        Args:
            db: Database session
            task_id: Task ID

        Returns:
            List of blocking task IDs
        """
        result = await db.execute(
            select(TaskDependency.task_id).where(TaskDependency.blocks_task_id == task_id)
        )
        return list(result.scalars().all())

    def _validate_status_transition(self, from_status: str, to_status: str) -> None:
        """Validate status transition.

        Args:
            from_status: Current status
            to_status: Target status

        Raises:
            InvalidStatusTransitionError: If transition is invalid
        """
        # Define valid transitions
        valid_transitions = {
            "pending": ["in_progress", "blocked", "failed"],
            "in_progress": ["completed", "blocked", "failed"],
            "blocked": ["pending", "in_progress", "failed"],
            "completed": [],  # Cannot transition from completed
            "failed": ["pending", "in_progress"],  # Can retry failed tasks
        }

        if from_status == to_status:
            return  # No transition

        allowed = valid_transitions.get(from_status, [])
        if to_status not in allowed:
            raise InvalidStatusTransitionError(0, from_status, to_status)

    def _task_to_response(
        self,
        task: Task,
        blocks_ids: list[int],
        blocked_by_ids: list[int],
    ) -> TaskResponse:
        """Convert Task model to TaskResponse.

        Args:
            task: Task model
            blocks_ids: List of blocked task IDs
            blocked_by_ids: List of blocking task IDs

        Returns:
            Task response
        """
        return TaskResponse(
            id=task.id,
            task_list_id=task.task_list_id,
            subject=task.subject,
            description=task.description,
            active_form=task.active_form,
            owner=task.owner,
            status=task.status,
            task_metadata=task.task_metadata,
            blocks=blocks_ids,
            blocked_by=blocked_by_ids,
            created_at=task.created_at,
            updated_at=task.updated_at,
            version=task.version,
        )

    async def _broadcast_task_update(
        self,
        event_type: str,
        task: Task,
        session_id: str | None = None,
    ) -> None:
        """Broadcast task update via WebSocket.

        Args:
            event_type: Type of event (task_created, task_updated, task_completed)
            task: Task model
            session_id: Optional session ID
        """
        try:
            manager = await TaskUpdateWebSocketManager.get_instance()
            message = TaskUpdateMessage(
                event_type=event_type,
                task_id=task.id,
                task_list_id=task.task_list_id,
                subject=task.subject,
                status=task.status,
                owner=task.owner,
                session_id=session_id,
                timestamp=task.updated_at.isoformat(),
            )
            await manager.broadcast_task_update(message)
            _logger.debug(
                "task_update_broadcast_queued",
                event_type=event_type,
                task_id=task.id,
            )
        except Exception as exc:
            _logger.warning(
                "task_update_broadcast_failed",
                event_type=event_type,
                task_id=task.id,
                error=str(exc),
            )
