"""PKCE (Proof Key for Code Exchange) implementation.

PKCE is an extension to the Authorization Code flow to prevent
authorization code interception attacks.
"""

from __future__ import annotations

import base64
import hashlib
import os
from typing import Tuple


def generate_code_verifier(length: int = 128) -> str:
    """Generate a random code verifier for PKCE.

    The code verifier is a cryptographically random string using characters
    [A-Z] / [a-z] / [0-9] / "-" / "." / "_" / "~".

    Args:
        length: Length of the code verifier (43-128 characters recommended)

    Returns:
        URL-safe base64-encoded random string
    """
    # Generate random bytes
    random_bytes = os.urandom(length)

    # Encode using URL-safe base64 (remove padding)
    code_verifier = base64.urlsafe_b64encode(random_bytes).decode().rstrip("=")

    # Ensure minimum length of 43 characters
    while len(code_verifier) < 43:
        random_bytes = os.urandom(length)
        code_verifier = base64.urlsafe_b64encode(random_bytes).decode().rstrip("=")

    return code_verifier


def generate_code_challenge(code_verifier: str, method: str = "S256") -> str:
    """Generate a code challenge from the code verifier.

    Args:
        code_verifier: The code verifier generated by generate_code_verifier()
        method: The transformation method ("S256" for SHA-256, "plain" for no transformation)

    Returns:
        URL-safe base64-encoded code challenge

    Raises:
        ValueError: If method is not supported
    """
    if method == "S256":
        # SHA-256 hash the code verifier
        hash_bytes = hashlib.sha256(code_verifier.encode()).digest()

        # Base64 URL-encode without padding
        code_challenge = base64.urlsafe_b64encode(hash_bytes).decode().rstrip("=")

        return code_challenge
    elif method == "plain":
        # No transformation
        return code_verifier
    else:
        raise ValueError(f"Unsupported code challenge method: {method}")


def generate_pkce_pair(method: str = "S256", verifier_length: int = 128) -> Tuple[str, str]:
    """Generate a PKCE code verifier and challenge pair.

    Args:
        method: The transformation method ("S256" for SHA-256, "plain" for no transformation)
        verifier_length: Length of the code verifier

    Returns:
        Tuple of (code_verifier, code_challenge)
    """
    code_verifier = generate_code_verifier(verifier_length)
    code_challenge = generate_code_challenge(code_verifier, method)
    return code_verifier, code_challenge
